### ISSUE TITLE
How to clear artifacts

### ISSUE THREAD

**Issue by volodyad** [argoproj/argo#3390] opened 2020-07-06 13:01 UTC
we are using minio as artifacts storage,
when flow is completed, i have manually delete the job (e.g. artifact-passing.yaml),
but in minio artifact is still present

Artifacts is ephemeral, and not needed after flow exectued.

What is the flow of deleting old artifacts?
Do we need to use artifacts at all, in case they are ephemeral? Maybe better to use pvc claims?

**Comment by alexec** [comment] 2020-07-07 15:37
Good question. We don't have any guidance on how to clean up your artifacts.

@jessesuen ?

**Comment by dcherman** [comment] 2020-07-07 18:25
FWIW, this is likely a duplicate of https://github.com/argoproj/argo/issues/3102

The case where the artifact repository is well known (like in your own installation) is pretty easy to handle - you can use a well-known keyFormat, then run a CronJob/CronWorkflow that periodically compares what exists in your artifact repository versus what Workflows exist (or have been archived) and delete files from your artifact store as necessary.

The general case as would need to be solved in the linked issue is actually a lot more complex due to the large variety of ways that you can authenticate to your artifact repository.

Off the top of my head:

* Static credentials
* IAM Roles for Service Accounts (or the equivalent on GCP, etc..)
* Single use secrets / sessions

In the case of the latter two, actually figuring out what actions you need to take in what namespaces using what service accounts is surprisingly tricky to solve for (which is why I don't have a proposed solution for that issue yet).  When you know exactly what artifact stores you're using with exactly what auth method (i.e. the end user case), implementing artifact GC is much easier to accomplish

**Comment by alexec** [comment] 2020-07-07 18:47
Is there anyway to set a TTLS of files in a bucket?

**Comment by ashrafgt** [comment] 2020-07-12 22:07
@alexec
For GCS-based artifact storage, [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) does the trick.

**Comment by alexec** [comment] 2020-07-13 14:45
S3: https://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html#intro-lifecycle-rules-actions

**Closed** 2020-09-18 15:53 UTC
Labels: question, wontfix
