### ISSUE TITLE
Argo CLI 2.11 does not support integers for parameter values 

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo#4191] opened 2020-10-02 14:10 UTC
## Summary 

What happened/what you expected to happen?
Upgrading my CLI to 2.11 (brew did the update) it breaks argo who can't get query my workflows anymore.
It breaks if any workflow uses an integer and not a string as a parameter value (see example below)

```
argo list    
FATA[0000] v1alpha1.WorkflowList.Items: v1alpha1.Workflows: v1alpha1.Workflow.Spec: 
v1alpha1.WorkflowSpec.Arguments: v1alpha1.Arguments.Parameters: []v1alpha1.Parameter: 
v1alpha1.Parameter.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,
"value":10}]},"entr|..., bigger context ...|uments":{"parameters":[{"name":"message","value":10}]},
"entrypoint":"whalesay","templates":[{"contai|...
```

## Diagnostics

What Kubernetes provider are you using? 
EKS

What version of Argo Workflows are you running? 
2.10

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: arguments-parameters
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: 10

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment] 2020-10-02 14:15
We're aware of this (duplicate of https://github.com/argoproj/argo/issues/4169 and https://github.com/argoproj/argo/issues/4141). We broke backwards compatibility with the 2.11 CLI. For now, please make sure that your `workflow-controller` and CLI are running on the same version.

FYI: We do not expect to break backwards compatibility like this, so this is an anomaly (see https://github.com/argoproj/argo/issues/4141#issuecomment-700788763)

cc @alexec

**Comment by brews** [comment] 2020-10-02 14:16
I also get this error on GKE 1.16.13 clusters with Argo 2.11.0 and 2.11.1.

Appears similar to #4141.

**Comment by alexec** [comment] 2020-10-02 16:12
Duplicate of #4141

**Closed by alexec** 2020-10-02 16:12 UTC
Labels: bug, duplicate
