### ISSUE TITLE
Argo ui websockets not working when deployed via namespace install

### ISSUE THREAD

**Issue by dfarr** [argoproj/argo#1200] opened 2019-01-30 21:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
When I install argo in namespace mode, with the [namespace install manifest](https://github.com/argoproj/argo/blob/master/manifests/namespace-install.yaml), websockets seem not to work in the UI.

**What you expected to happen**:
New workflows to appear automatically in the UI via a websocket connection.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl apply -f https://raw.githubusercontent.com/argoproj/argo/master/manifests/namespace-install.yaml
...
$ argo submit https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml -n argo
```

If you have your UI open, the new workflow will not appear until you do a manual refresh. The same goes for state updates of a running workflow.

**Anything else we need to know?**:
Funny enough, if I remove the `FORCE_NAMESPACE_ISOLATION` env variable, and submit a workflow to the *default* namespace. The websocket will pick up this workflow and display it in the UI automatically. However, because argo has been deployed in namespace mode, the workflow will forever be pending.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2018-12-13T19:44:10Z"
  compiler: gc
  gitCommit: eec55b9ba98609a46fee712359c7b5b365bdd920
  gitTreeState: clean
  gitVersion: v1.13.1
  goVersion: go1.11.2
  major: "1"
  minor: "13"
  platform: darwin/amd64
serverVersion:
  buildDate: "2018-05-21T09:05:37Z"
  compiler: gc
  gitCommit: 2bba0127d85d5a46ab4b778548be28623b32d0b0
  gitTreeState: clean
  gitVersion: v1.10.3
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Comment by alexmt** [comment] 2019-01-30 21:18
Hello @dfarr , the issue was fixed in master. Please check https://github.com/argoproj/argo/issues/1101#issuecomment-445318979 for workaround

**Comment by alexmt** [comment] 2019-01-30 21:19
Closing it as a duplicate of https://github.com/argoproj/argo/issues/1101

**Closed by alexmt** 2019-01-30 21:19 UTC

**Comment by dfarr** [comment] 2019-01-30 22:10
Nice! Thank you
