### ISSUE TITLE
500 Internal Server: load artifact from S3

### ISSUE THREAD

**Issue by wanghong230** [argoproj/argo#985] opened 2018-09-06 23:37 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:
```
time="2018-09-06T23:20:31Z" level=fatal msg="500 Internal Server Error\ngithub.com/argoproj/argo/errors.Wrap\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:87\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:70\ngithub.com/argoproj/argo/workflow/artifacts/s3.(*S3ArtifactDriver).Load\n\t/root/go/src/github.com/argoproj/argo/workflow/artifacts/s3/s3.go:65\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).LoadArtifacts\n\t/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:134\ngithub.com/argoproj/argo/cmd/argoexec/commands.loadArtifacts\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:35\ngithub.com/argoproj/argo/cmd/argoexec/commands.glob..func1\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:17\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:750\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:831\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:784\nmain.main\n\t/root/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:195\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337"
```
**What you expected to happen**:

It should be working.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by kshamajain99** [comment] 2018-12-20 21:19
duplicate of #1081

**Comment by jessesuen** [comment] 2019-01-22 22:13
Closing as dup

**Closed by jessesuen** 2019-01-22 22:13 UTC
