### ISSUE TITLE
Cannot use input parameters in kube yaml resources section

### ISSUE THREAD

**Issue by strin** [argoproj/argo#1015] opened 2018-09-24 06:51 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT.

**What happened**:

In workflow.yaml

```
  - name: train
    inputs:
      parameters:
      - name: image
      - name: company
      - name: dataset
      - name: clusters
      - name: checkpoint
        default: ""
      - name: config
        default: ""
      - name: memory
        default: "10Gi"
    container:
      image: "quay.io/cresta/suggestions-api:{{inputs.parameters.image}}"
      args: [
          "train", 
          "--company", "{{inputs.parameters.company}}",
          "--dataset", "{{inputs.parameters.dataset}}",
          "--clusters", "{{inputs.parameters.clusters}}",
          "--config", "{{inputs.parameters.config}}",
          "--checkpoint", "{{inputs.parameters.checkpoint}}"
      ]
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          memory: "{{inputs.parameters.memory}}"
```

Argo works correctly, when the request section is not included

```
        requests:
          memory: "{{inputs.parameters.memory}}"
```

But with the memory requests, it throws an error in CLI:

```
2018/09/23 23:48:33 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**What you expected to happen**:

Argo passes input parameters to the resource section of kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

Use my yaml file as shown above, and run `argo submit workflow.yaml`

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:51:40Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2017-11-09T07:26:41Z
  compiler: gc
  gitCommit: f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd
  gitTreeState: clean
  gitVersion: v1.8.3
  goVersion: go1.9.2
  major: "1"
  minor: "8"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-02T23:42:40Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.5
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment] 2018-09-24 08:45
This is a duplicate of #703. This is a known limitation without a solution since we have no way of customizing the marshaling function of the imported Container data structure.

**Closed by jessesuen** 2018-09-24 08:45 UTC
