### ISSUE TITLE
Issues while running CI workflow with Argo Lite on Minikube 

### ISSUE THREAD

**Issue by nkhare** [argoproj/argo#400] opened 2017-10-24 08:33 UTC
After configuring the Argo Lite on Minikube, I am running following command to submit the workflow :-

```
$ argo job submit example-workflow-approval  --repo https://github.com/argoproj/ci-workflow.git --local --config argo-lite-kube
```
Please note that I have removed the approval step from workflow. 

At random `test1`, `test2` and `test3` fails. Sometime one test runs and sometimes 2 of them runs. 

When test fails, I get following inside the container 

```
# cd /src && ls -ltr && go test -v
total 2248
-rw-r--r-- 1 root root 2296264 Oct 24 07:31 main
drwxr-xr-x 4 root root    4096 Oct 24 07:31 CODE
can't load package: package .: no buildable Go source files in /src
```

And when test pass, I get following inside the container 

```
# ls /src
AX_Pub.png  README.md  approval.png  axchecker_docker.sh  main	main.go  main_test.go
# cd /src && ls -ltr && go test -v
total 2308
-rw-r--r-- 1 root root     248 Oct 24 07:27 main_test.go
-rw-r--r-- 1 root root    6256 Oct 24 07:27 main.go
-rw-r--r-- 1 root root     985 Oct 24 07:27 axchecker_docker.sh
-rw-r--r-- 1 root root   39922 Oct 24 07:27 approval.png
-rw-r--r-- 1 root root     257 Oct 24 07:27 README.md
-rw-r--r-- 1 root root     816 Oct 24 07:27 AX_Pub.png
-rw-r--r-- 1 root root 2296264 Oct 24 07:27 main
```

To it looks that artifacts are not getting copied correctly, inside the test containers.

**Comment by alexmt** [comment] 2017-10-27 17:07
Issue is duplicate of https://github.com/argoproj/argo/issues/375 . I'm working on fixing it.

**Closed by alexmt** 2017-10-27 17:07 UTC
Labels: bug
