### ISSUE TITLE
withItems mangles strings with percent signs

### ISSUE THREAD

**Issue by TRManderson** [argoproj/argo#2477] opened 2020-03-19 07:18 UTC
In argo 2.6.3, when providing a string with a percent sign to `withItems`, it's mangled to add extra content that seems like it's in the style of Go format strings (this might be a red herring though).

Minimal reproduction, the single percent string procudes `$!(NOVERB)` while the double percent produces a single percent sign.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
      - - name: whalesay
          template: whalesay
          arguments:
            parameters:
              - name: words
                value: "{{item}}"
          withItems:
            - "this is a percent sign: %" # prints "this is a percent sign: %!(NOVERB)"
            - "this is two percent signs: %%" # prints "this is two percent signs: %"
  - name: whalesay
    inputs:
      parameters:
        - name: words
    container:
      image: docker/whalesay:latest
      command: [echo]
      args: ["{{inputs.parameters.words}}"]
```

**Environment**:
- Kubernetes version :
```
serverVersion:
  buildDate: "2020-02-07T01:31:02Z"
  compiler: gc
  gitCommit: 502bfb383169b124d87848f89e17a04b9fc1f6f0
  gitTreeState: clean
  gitVersion: v1.14.9-eks-502bfb
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment] 2020-03-19 16:06
Does this work in earlier versions?

**Comment by TRManderson** [comment] 2020-03-20 02:22
It works in 2.4.2 and 2.4.3

**Comment by simster7** [comment] 2020-03-23 16:42
@TRManderson I spent some time trying to look into this, but it seems like the issue is within the libraries that we use to do our YAML unmarsahlling. Best I can do right now is to suggest that you escape your percentage signs with another percentage sign. I.e. `%% = %, %%%%= %%`. You seem to have already been on the right track here.

**Comment by simster7** [comment] 2020-03-23 16:44
Going to close this, but feel free to chime in if you think this isn't resolved properly

**Closed by simster7** 2020-03-23 16:44 UTC
Labels: bug, good first issue, help wanted, workaround
