### ISSUE TITLE
in comparator does not work when there is only one value inside the parenthesis

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo#4356] opened 2020-10-23 09:00 UTC
## Summary 
"in" is now supported in conditionals but I am getting an error when trying to use it with only one value inside the parenthesis

Here is the error I got:
```
Failed to evaluate 'when' expresion 'a in (a)': Value 'a' cannot be used with the comparator 'in', it is not a number
```
However if I use `when: "a in (a,b)"` then it works.
## Diagnostics

What Kubernetes provider are you using? 
Kubernetes in IBM cloud

What version of Argo Workflows are you running? 
v2.11.6

Here's an example of a workflow that fails
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-bash-
spec:
  entrypoint: bash-script-example
  templates:
  - name: bash-script-example
    steps:
    - - name: schedule
        template: schedule
    - - name: a
        template: print-message
        when: "a in {{steps.schedule.outputs.result}}"
        arguments:
          parameters:
          - name: message
            value: "I am step A"
      - name: b
        template: print-message
        when: "b in {{steps.schedule.outputs.result}}"
        arguments:
          parameters:
          - name: message
            value: "I am step B"
      - name: c
        template: print-message
        when: "c in {{steps.schedule.outputs.result}}"
        arguments:
          parameters:
          - name: message
            value: "I am step C"

  - name: schedule
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo '(a)'"] # replacing '(a)' with '(a,b)' works
  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2020-10-23 15:10
Would you like to dig into the code and see if you can find the cause?

**Comment by lueenavarro** [comment] 2020-10-23 16:08
In workflow/controller/steps.go, there is this function. Its probably line 321 that is causing the error
```
func shouldExecute(when string) (bool, error) {
	if when == "" {
		return true, nil
	}
	expression, err := govaluate.NewEvaluableExpression(when)
	if err != nil {
		if strings.Contains(err.Error(), "Invalid token") {
			return false, errors.Errorf(errors.CodeBadRequest, "Invalid 'when' expression '%s': %v (hint: try wrapping the affected expression in quotes (\"))", when, err)
		}
		return false, errors.Errorf(errors.CodeBadRequest, "Invalid 'when' expression '%s': %v", when, err)
	}
	// The following loop converts govaluate variables (which we don't use), into strings. This
	// allows us to have expressions like: "foo != bar" without requiring foo and bar to be quoted.
	tokens := expression.Tokens()
	for i, tok := range tokens {
		switch tok.Kind {
		case govaluate.VARIABLE:
			tok.Kind = govaluate.STRING
		default:
			continue
		}
		tokens[i] = tok
	}
	expression, err = govaluate.NewEvaluableExpressionFromTokens(tokens)
	if err != nil {
		return false, errors.InternalWrapErrorf(err, "Failed to parse 'when' expression '%s': %v", when, err)
	}
	result, err := expression.Evaluate(nil)
	if err != nil {
		return false, errors.InternalWrapErrorf(err, "Failed to evaluate 'when' expresion '%s': %v", when, err)
	}
	boolRes, ok := result.(bool)
	if !ok {
		return false, errors.Errorf(errors.CodeBadRequest, "Expected boolean evaluation for '%s'. Got %v", when, result)
	}
	return boolRes, nil
}
```

**Comment by lueenavarro** [comment] 2020-10-23 16:38
This does not seem to be a bug in argo but a bug in govaluate. I found this issue in their github.
[https://github.com/Knetic/govaluate/issues/79](url)

**Comment by simster7** [comment] 2020-10-27 15:33
Closed as a non-argo issue. As a thought, if you want `a in (a)` why not simply do `a == a`?

**Closed by simster7** 2020-10-27 15:33 UTC
Labels: bug

**Comment by lueenavarro** [comment] 2020-10-27 15:47
because in my application, the value inside the parenthesis is dynamically generated by another step. 

my solution was to add random characters as placeholders to make sure that there are always at least two items.
