### ISSUE TITLE
Expose execution/retry attempt number as variable

### ISSUE THREAD

**Issue by seddonm1** [argoproj/argo#2898] opened 2020-04-29 21:54 UTC
# Summary

Currently there is no way of exposing the retry attempt number to a pod to change the logic depending on whether the workflow is executing correctly (the first execution attempt) or if it has already failed (one of *n* retry attempts). 

# Motivation

Being able to determine the execution attempt number at the child container level means that those containers can request different resources dependent on the execution attempt. 

For example, a container may require more RAM when running retry `1` than on retry `0` to allow it to meet a service level agreement - or just to allow it to succeed if initial resources were insufficient.

# Proposal

This proposal is to expose either `pod.executionAttempt` or `pod.retryAttempt`:

- `pod.executionAttempt` (could be shortened to `pod.execution`) would support both `retryStrategy` stages and non-`retryStrategy` stages and start at `1`.

- `pod.retryAttempt` would support only `retryStrategy` stages and start at `0` indicating no retry and `n` for the attempt number.

I have built this functionality with `retryAttempt` and tests are passing but wanted community input as to whether this feature would be beneficial and which approach (`executionAttempt` vs `retryAttempt`) makes more logical sense.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by danxmoran** [comment] 2020-04-30 04:23
Related to #2808 (the top-level description is about metrics, but the proposed solution is to expose something like the “retryAttempt” variable mentioned here)

**Comment by simster7** [comment] 2020-04-30 15:15
Closing as duplicate of #2808

**Closed by simster7** 2020-04-30 15:15 UTC
Labels: enhancement
