### ISSUE TITLE
UI node graph creates zigzags when some nodes have retries but others don't

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo#3884] opened 2020-08-28 01:00 UTC
## Summary 

If a node is hidden, it should not affect where lines in the node graph go.

In the image below, you can see zigzag lines which are edges connected to nodes that are not being displayed.

![image](https://user-images.githubusercontent.com/854789/91509460-219b1380-e88f-11ea-880b-8726dc6dbc2e.png)

## Diagnostics

What version of Argo Workflows are you running?

2.10

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by foobarbecue** [comment] 2020-08-28 01:04
I see now that this has to do with retries, and it's a little complicated to see what the correct approach to drawing this is.

**Comment by simster7** [comment] 2020-08-31 14:56
> The core issue is that a node that does a retry occupies one more vertical level than when the same type of node does not do a retry.

Correct. I've actually thought about this before. It's not shown, but every vertex of the "zig zag" is actually a hidden node of type `Retry`, which is why the zig zag happens.

I'll see if I can find a clear solution to this

**Comment by foobarbecue** [comment] 2020-09-01 04:51
There's another related issue. At some point, the graph rendering changed so that nodes are pulled to the center instead of being placed vertically in line with their parent. This makes it much harder to follow the graph visually, and it doesn't actually save any space. Here's an example:

![image](https://user-images.githubusercontent.com/854789/91796011-02c0b800-ebd4-11ea-9d6c-669b298d3620.png)

The four strings of nodes on the left should go straight downwards rather than converging.

The only time nodes should converge is when there are multiple parents to a single child node (the graph is actually converging).

**Comment by simster7** [comment] 2020-09-01 16:11
Hi @foobarbecue, we are aware of this issue (duplicate of https://github.com/argoproj/argo/issues/3595). The reason behind the change is that it is actually much faster to render DAGs this way (https://github.com/argoproj/argo/pull/2959) which becomes significant when rendering very large workflows.

I am looking into some sort of compromise between performance and UX so that ideally both concerns are taken care of.

**Comment by alexec** [comment] 2020-09-01 16:27
I'm not sure these are fixable. From changing from Dagre (which does nice layouts) to Coffman-Graham Sorter (which is fast) we swapped attractive layout for fast rendering. I think the zig-zag layout is caused by the fact that the sorter lays things out in a table.

**Comment by foobarbecue** [comment] 2020-09-01 17:41
I see, tricky for sure. Maybe in an ideal world you can choose between the two layout methods.

Anyway, we should confine this issue to discussing the elimination of the elbows in the lines for non-displayed nodes, as opposed to the other issue I mentioned which is indeed a duplicate of #3595 .

**Comment by alexec** [comment] 2020-09-01 18:03
> choose between the two layout methods.

Yes! I've raised an issue with https://github.com/dagrejs/dagre/issues/305 to implement the faster sorter. Maybe we need to fork it.

**Comment by foobarbecue** [comment] 2020-09-07 01:51
Here's a special case... this happened when I suspended a workflow which was a retry. Not sure if I'll be able to repro it. Interesting, though!

![image](https://user-images.githubusercontent.com/854789/92341227-e7412b80-f071-11ea-9473-20913abf8b0e.png)

**Comment by simster7** [comment] 2020-09-08 16:25
Will close this as duplicate of #3595, but please feel free to keep adding more examples/workflows with this issue

**Comment by simster7** [comment] 2020-09-08 16:30
On further inspection, I actually don't think this is a _full_ duplicate of #3595. While this problem would not be present with the pleasant but slow DAG renderer, we're not planning to fully revert to it (our current plan is to use a mix of both), so this will need to be fixed with the chaotic but fast DAG renderer as well

**Comment by simster7** [comment] 2020-09-15 17:36
@foobarbecue Could you provide a "live" workflow to reproduce this? I.e. one that has `Workflow.Status.Nodes` set that you get by running `kubectl get wf <NAME> -o yaml`.

It doesn't have to be running, in fact it'd be better if it was finished

**Comment by simster7** [comment] 2020-09-30 14:15
@foobarbecue Little bump ☝️. Planning on starting work on this soon 🙂

**Comment by simster7** [comment] 2020-12-04 14:39
Closing for no

**Closed by simster7** 2020-12-04 14:39 UTC
Labels: bug, wontfix
