### ISSUE TITLE
Argo workflows ttlStrategy does not work as expected after upgrading to 2.11.3

### ISSUE THREAD

**Issue by akonale** [argoproj/argo#4393] opened 2020-10-27 15:21 UTC
## Summary 
Hi I have `ttlStrategy.secondsAfterCompletion` set at global level to remove old workflows. Workflows are scheduled by argo events every one hour. ttlStrategy used to work just fine while running argo workflows version `2.7`. But after upgrading to `2.11.3`, workflows doesn't get cleaned up correctly. Looking at controller logs, ttl controller runs very irregularly. When I restart the controller, initially it runs every ~20 min for few hours. After that ttl controller runs very randomly, for eg. after 3 hours, after 5 hours etc. Even when it runs, it doesn't clean up the resources properly. I have confirmed that the newly created workflows gets `ttlStrategy.secondsAfterCompletion` property in them. Hourly workflows gets scheduled properly without problems. Could you please help me fix it ?

## Diagnostics

> What Kubernetes provider are you using? 
Vanilla kubernetes, v1.17

> What version of Argo Workflows are you running? 
v2.11.3

```yaml
# argo-workflow-controller-configmap.yaml

workflowDefaults:
  spec:
    ttlStrategy:
      secondsAfterCompletion: 21600
```

```
Paste the logs from the workflow controller:
time="2020-10-26T11:34:18Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-10-26T11:34:19Z" level=info msg="Found Workflow sensor-workflowsjnql set expire at 2020-10-26 11:09:23 +0000 UTC (-24m56.106914078s from now)"
time="2020-10-26T11:34:19Z" level=info msg="Found Workflow sensor-workflowzbd75 set expire at 2020-10-26 10:49:26 +0000 UTC (-44m53.110287398s from now)"
time="2020-10-26T11:34:19Z" level=info msg="Started workflow TTL worker"
time="2020-10-26T11:34:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowsjnql"
time="2020-10-26T11:34:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowzbd75"
time="2020-10-26T11:54:19Z" level=info msg="Found Workflow sensor-workflow4q2vc set expire at 2020-10-26 12:10:05 +0000 UTC (15m45.923462177s from now)"
time="2020-10-26T11:54:19Z" level=info msg="Found Workflow sensor-workflown4blq set expire at 2020-10-26 12:00:52 +0000 UTC (6m32.920688315s from now)"
time="2020-10-26T11:54:19Z" level=info msg="Found Workflow sensor-workflowtw68h set expire at 2020-10-26 12:00:53 +0000 UTC (6m33.906615672s from now)"
time="2020-10-26T11:54:19Z" level=info msg="Found Workflow sensor-workflow982kd set expire at 2020-10-26 12:09:19 +0000 UTC (14m59.899988865s from now)"
time="2020-10-26T12:00:52Z" level=info msg="Deleting TTL expired workflow sensor-workflown4blq"
time="2020-10-26T12:00:52Z" level=info msg="Found Workflow sensor-workflown4blq set expire at 2020-10-26 12:00:52 +0000 UTC (-17.412754ms from now)"
time="2020-10-26T12:00:53Z" level=info msg="Deleting TTL expired workflow sensor-workflowtw68h"
time="2020-10-26T12:00:53Z" level=info msg="Found Workflow sensor-workflowtw68h set expire at 2020-10-26 12:00:53 +0000 UTC (-24.081736ms from now)"
time="2020-10-26T12:09:19Z" level=info msg="Deleting TTL expired workflow sensor-workflow982kd"
time="2020-10-26T12:09:19Z" level=info msg="Found Workflow sensor-workflow982kd set expire at 2020-10-26 12:09:19 +0000 UTC (-21.480536ms from now)"
time="2020-10-26T12:10:05Z" level=info msg="Deleting TTL expired workflow sensor-workflow4q2vc"
time="2020-10-26T12:10:05Z" level=info msg="Found Workflow sensor-workflow4q2vc set expire at 2020-10-26 12:10:05 +0000 UTC (-25.208689ms from now)"
time="2020-10-26T12:14:19Z" level=info msg="Found Workflow sensor-workflowtgr9p set expire at 2020-10-26 12:26:05 +0000 UTC (11m45.920548141s from now)"
time="2020-10-26T12:14:19Z" level=info msg="Found Workflow sensor-workflowcw5z2 set expire at 2020-10-26 12:14:53 +0000 UTC (33.896253123s from now)"
time="2020-10-26T12:14:53Z" level=info msg="Deleting TTL expired workflow sensor-workflowcw5z2"
time="2020-10-26T12:14:53Z" level=info msg="Found Workflow sensor-workflowcw5z2 set expire at 2020-10-26 12:14:53 +0000 UTC (-23.481716ms from now)"
time="2020-10-26T12:26:05Z" level=info msg="Deleting TTL expired workflow sensor-workflowtgr9p"
time="2020-10-26T12:26:05Z" level=info msg="Found Workflow sensor-workflowtgr9p set expire at 2020-10-26 12:26:05 +0000 UTC (-24.186563ms from now)"
time="2020-10-26T12:54:19Z" level=info msg="Found Workflow sensor-workflowqk4cq set expire at 2020-10-26 13:00:53 +0000 UTC (6m33.914411841s from now)"
time="2020-10-26T12:54:19Z" level=info msg="Found Workflow sensor-workflowcrqwm set expire at 2020-10-26 13:10:02 +0000 UTC (15m42.905953463s from now)"
time="2020-10-26T12:54:19Z" level=info msg="Found Workflow sensor-workflowf2596 set expire at 2020-10-26 13:00:53 +0000 UTC (6m33.900739538s from now)"
time="2020-10-26T13:00:53Z" level=info msg="Deleting TTL expired workflow sensor-workflowf2596"
time="2020-10-26T13:00:53Z" level=info msg="Deleting TTL expired workflow sensor-workflowqk4cq"
time="2020-10-26T13:00:53Z" level=info msg="Found Workflow sensor-workflowf2596 set expire at 2020-10-26 13:00:53 +0000 UTC (-21.788945ms from now)"
time="2020-10-26T13:00:53Z" level=info msg="Found Workflow sensor-workflowqk4cq set expire at 2020-10-26 13:00:53 +0000 UTC (-30.385882ms from now)"
time="2020-10-26T13:10:02Z" level=info msg="Deleting TTL expired workflow sensor-workflowcrqwm"
time="2020-10-26T13:10:02Z" level=info msg="Found Workflow sensor-workflowcrqwm set expire at 2020-10-26 13:10:02 +0000 UTC (-23.391857ms from now)"
time="2020-10-26T13:14:19Z" level=info msg="Found Workflow sensor-workflow4qscm set expire at 2020-10-26 13:15:18 +0000 UTC (58.922397425s from now)"
time="2020-10-26T13:14:19Z" level=info msg="Found Workflow sensor-workflow5j6ms set expire at 2020-10-26 13:26:20 +0000 UTC (12m0.91302406s from now)"
time="2020-10-26T13:14:19Z" level=info msg="Found Workflow sensor-workflow2lk8j set expire at 2020-10-26 13:15:24 +0000 UTC (1m4.903810012s from now)"
time="2020-10-26T13:15:18Z" level=info msg="Deleting TTL expired workflow sensor-workflow4qscm"
time="2020-10-26T13:15:18Z" level=info msg="Found Workflow sensor-workflow4qscm set expire at 2020-10-26 13:15:18 +0000 UTC (-27.065953ms from now)"
time="2020-10-26T13:15:18Z" level=info msg="Found Workflow sensor-workflow4qscm set expire at 2020-10-26 13:15:18 +0000 UTC (-27.354212ms from now)"
time="2020-10-26T13:15:24Z" level=info msg="Deleting TTL expired workflow sensor-workflow2lk8j"
time="2020-10-26T13:15:24Z" level=info msg="Found Workflow sensor-workflow2lk8j set expire at 2020-10-26 13:15:24 +0000 UTC (-25.833731ms from now)"
time="2020-10-26T13:26:20Z" level=info msg="Deleting TTL expired workflow sensor-workflow5j6ms"
time="2020-10-26T13:26:20Z" level=info msg="Found Workflow sensor-workflow5j6ms set expire at 2020-10-26 13:26:20 +0000 UTC (-24.915764ms from now)"
time="2020-10-26T13:54:19Z" level=info msg="Found Workflow sensor-workflowngx66 set expire at 2020-10-26 14:00:58 +0000 UTC (6m38.921386814s from now)"
time="2020-10-26T13:54:19Z" level=info msg="Found Workflow sensor-workflowkbshf set expire at 2020-10-26 14:09:30 +0000 UTC (15m10.921151883s from now)"
time="2020-10-26T13:54:19Z" level=info msg="Found Workflow sensor-workflowlsprk set expire at 2020-10-26 14:01:00 +0000 UTC (6m40.914028714s from now)"
time="2020-10-26T14:00:58Z" level=info msg="Deleting TTL expired workflow sensor-workflowngx66"
time="2020-10-26T14:00:58Z" level=info msg="Found Workflow sensor-workflowngx66 set expire at 2020-10-26 14:00:58 +0000 UTC (-20.800353ms from now)"
time="2020-10-26T14:01:00Z" level=info msg="Deleting TTL expired workflow sensor-workflowlsprk"
time="2020-10-26T14:01:00Z" level=info msg="Found Workflow sensor-workflowlsprk set expire at 2020-10-26 14:01:00 +0000 UTC (-20.193416ms from now)"
time="2020-10-26T14:09:30Z" level=info msg="Deleting TTL expired workflow sensor-workflowkbshf"
time="2020-10-26T14:09:30Z" level=info msg="Found Workflow sensor-workflowkbshf set expire at 2020-10-26 14:09:30 +0000 UTC (-24.344185ms from now)"
time="2020-10-26T14:14:19Z" level=info msg="Found Workflow sensor-workflowkr8ch set expire at 2020-10-26 14:29:26 +0000 UTC (15m6.915108117s from now)"
time="2020-10-26T14:14:19Z" level=info msg="Found Workflow sensor-workflowghf4v set expire at 2020-10-26 14:29:18 +0000 UTC (14m58.902668379s from now)"
time="2020-10-26T14:29:18Z" level=info msg="Deleting TTL expired workflow sensor-workflowghf4v"
time="2020-10-26T14:29:18Z" level=info msg="Found Workflow sensor-workflowghf4v set expire at 2020-10-26 14:29:18 +0000 UTC (-24.811944ms from now)"
time="2020-10-26T14:29:26Z" level=info msg="Deleting TTL expired workflow sensor-workflowkr8ch"
time="2020-10-26T14:29:26Z" level=info msg="Found Workflow sensor-workflowkr8ch set expire at 2020-10-26 14:29:26 +0000 UTC (-27.756759ms from now)"
time="2020-10-26T14:29:26Z" level=info msg="Found Workflow sensor-workflowkr8ch set expire at 2020-10-26 14:29:26 +0000 UTC (-27.756755ms from now)"
time="2020-10-26T14:34:19Z" level=info msg="Found Workflow sensor-workflowdr2n2 set expire at 2020-10-26 14:42:12 +0000 UTC (7m52.897275916s from now)"
time="2020-10-26T14:42:12Z" level=info msg="Deleting TTL expired workflow sensor-workflowdr2n2"
time="2020-10-26T14:42:12Z" level=info msg="Found Workflow sensor-workflowdr2n2 set expire at 2020-10-26 14:42:12 +0000 UTC (-18.889949ms from now)"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflow2dqt7 set expire at 2020-10-26 15:28:57 +0000 UTC (14m37.920656504s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflow5zq4b set expire at 2020-10-26 15:15:30 +0000 UTC (1m10.906018731s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflowjxwvg set expire at 2020-10-26 15:00:52 +0000 UTC (-13m27.096169835s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowjxwvg"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflowv8l5s set expire at 2020-10-26 15:16:35 +0000 UTC (2m15.89716767s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflowwl477 set expire at 2020-10-26 15:00:54 +0000 UTC (-13m25.103880196s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflow4mlxr set expire at 2020-10-26 15:09:08 +0000 UTC (-5m11.105803616s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowwl477"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflowjxwvg set expire at 2020-10-26 15:00:52 +0000 UTC (-13m27.111192233s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Deleting TTL expired workflow sensor-workflow4mlxr"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflowwl477 set expire at 2020-10-26 15:00:54 +0000 UTC (-13m25.119348792s from now)"
time="2020-10-26T15:14:19Z" level=info msg="Found Workflow sensor-workflow4mlxr set expire at 2020-10-26 15:09:08 +0000 UTC (-5m11.131411242s from now)"
time="2020-10-26T15:15:30Z" level=info msg="Deleting TTL expired workflow sensor-workflow5zq4b"
time="2020-10-26T15:15:30Z" level=info msg="Found Workflow sensor-workflow5zq4b set expire at 2020-10-26 15:15:30 +0000 UTC (-21.261812ms from now)"
time="2020-10-26T15:16:35Z" level=info msg="Deleting TTL expired workflow sensor-workflowv8l5s"
time="2020-10-26T15:16:35Z" level=info msg="Found Workflow sensor-workflowv8l5s set expire at 2020-10-26 15:16:35 +0000 UTC (-22.284327ms from now)"
time="2020-10-26T15:28:57Z" level=info msg="Deleting TTL expired workflow sensor-workflow2dqt7"
time="2020-10-26T15:28:57Z" level=info msg="Found Workflow sensor-workflow2dqt7 set expire at 2020-10-26 15:28:57 +0000 UTC (-31.257944ms from now)"
time="2020-10-26T15:54:19Z" level=info msg="Found Workflow sensor-workflowwl5j9 set expire at 2020-10-26 16:00:53 +0000 UTC (6m33.91395288s from now)"
time="2020-10-26T15:54:19Z" level=info msg="Found Workflow sensor-workflowfvnvc set expire at 2020-10-26 16:09:42 +0000 UTC (15m22.912749537s from now)"
time="2020-10-26T15:54:19Z" level=info msg="Found Workflow sensor-workflow568s8 set expire at 2020-10-26 16:00:57 +0000 UTC (6m37.905928692s from now)"
time="2020-10-26T16:00:53Z" level=info msg="Deleting TTL expired workflow sensor-workflowwl5j9"
time="2020-10-26T16:00:53Z" level=info msg="Found Workflow sensor-workflowwl5j9 set expire at 2020-10-26 16:00:53 +0000 UTC (-19.598602ms from now)"
time="2020-10-26T16:00:57Z" level=info msg="Deleting TTL expired workflow sensor-workflow568s8"
time="2020-10-26T16:00:57Z" level=info msg="Found Workflow sensor-workflow568s8 set expire at 2020-10-26 16:00:57 +0000 UTC (-21.062745ms from now)"
time="2020-10-26T16:09:42Z" level=info msg="Deleting TTL expired workflow sensor-workflowfvnvc"
time="2020-10-26T16:09:42Z" level=info msg="Found Workflow sensor-workflowfvnvc set expire at 2020-10-26 16:09:42 +0000 UTC (-17.174316ms from now)"
time="2020-10-26T16:14:19Z" level=info msg="Found Workflow sensor-workflow67fkf set expire at 2020-10-26 16:21:28 +0000 UTC (7m8.916640287s from now)"
time="2020-10-26T16:14:19Z" level=info msg="Found Workflow sensor-workflowscqwf set expire at 2020-10-26 16:23:10 +0000 UTC (8m50.911440022s from now)"
time="2020-10-26T16:21:28Z" level=info msg="Deleting TTL expired workflow sensor-workflow67fkf"
time="2020-10-26T16:21:28Z" level=info msg="Found Workflow sensor-workflow67fkf set expire at 2020-10-26 16:21:28 +0000 UTC (-28.086543ms from now)"
time="2020-10-26T16:23:10Z" level=info msg="Deleting TTL expired workflow sensor-workflowscqwf"
time="2020-10-26T16:23:10Z" level=info msg="Found Workflow sensor-workflowscqwf set expire at 2020-10-26 16:23:10 +0000 UTC (-19.981737ms from now)"
time="2020-10-26T16:34:19Z" level=info msg="Found Workflow sensor-workflowcrbvf set expire at 2020-10-26 16:53:21 +0000 UTC (19m1.894739864s from now)"
time="2020-10-26T16:53:21Z" level=info msg="Deleting TTL expired workflow sensor-workflowcrbvf"
time="2020-10-26T16:53:21Z" level=info msg="Found Workflow sensor-workflowcrbvf set expire at 2020-10-26 16:53:21 +0000 UTC (-25.595446ms from now)"
time="2020-10-26T16:54:19Z" level=info msg="Found Workflow sensor-workflow8pp4n set expire at 2020-10-26 17:00:53 +0000 UTC (6m33.908356413s from now)"
time="2020-10-26T16:54:19Z" level=info msg="Found Workflow sensor-workflowlmbrn set expire at 2020-10-26 16:58:09 +0000 UTC (3m49.901698899s from now)"
time="2020-10-26T16:54:19Z" level=info msg="Found Workflow sensor-workflowmbpd5 set expire at 2020-10-26 17:00:54 +0000 UTC (6m34.896928332s from now)"
time="2020-10-26T16:58:09Z" level=info msg="Deleting TTL expired workflow sensor-workflowlmbrn"
time="2020-10-26T16:58:09Z" level=info msg="Found Workflow sensor-workflowlmbrn set expire at 2020-10-26 16:58:09 +0000 UTC (-31.770994ms from now)"
time="2020-10-26T17:00:53Z" level=info msg="Deleting TTL expired workflow sensor-workflow8pp4n"
time="2020-10-26T17:00:53Z" level=info msg="Found Workflow sensor-workflow8pp4n set expire at 2020-10-26 17:00:53 +0000 UTC (-16.466566ms from now)"
time="2020-10-26T17:00:54Z" level=info msg="Deleting TTL expired workflow sensor-workflowmbpd5"
time="2020-10-26T17:00:54Z" level=info msg="Found Workflow sensor-workflowmbpd5 set expire at 2020-10-26 17:00:54 +0000 UTC (-17.586007ms from now)"
time="2020-10-26T17:14:19Z" level=info msg="Found Workflow sensor-workflowj5kr9 set expire at 2020-10-26 17:32:11 +0000 UTC (17m51.901951436s from now)"
time="2020-10-26T17:14:19Z" level=info msg="Found Workflow sensor-workflowmtcj2 set expire at 2020-10-26 17:15:03 +0000 UTC (43.89435212s from now)"
time="2020-10-26T17:15:03Z" level=info msg="Deleting TTL expired workflow sensor-workflowmtcj2"
time="2020-10-26T17:15:03Z" level=info msg="Found Workflow sensor-workflowmtcj2 set expire at 2020-10-26 17:15:03 +0000 UTC (-19.958248ms from now)"
time="2020-10-26T17:32:11Z" level=info msg="Deleting TTL expired workflow sensor-workflowj5kr9"
time="2020-10-26T17:32:11Z" level=info msg="Found Workflow sensor-workflowj5kr9 set expire at 2020-10-26 17:32:11 +0000 UTC (-28.875304ms from now)"
time="2020-10-26T17:54:19Z" level=info msg="Found Workflow sensor-workflow45mvg set expire at 2020-10-26 18:00:55 +0000 UTC (6m35.915016s from now)"
time="2020-10-26T17:54:19Z" level=info msg="Found Workflow sensor-workflowbdf4b set expire at 2020-10-26 17:59:07 +0000 UTC (4m47.904634003s from now)"
time="2020-10-26T17:54:19Z" level=info msg="Found Workflow sensor-workflow75p5w set expire at 2020-10-26 17:57:17 +0000 UTC (2m57.901047202s from now)"
time="2020-10-26T17:54:19Z" level=info msg="Found Workflow sensor-workflowkg2mn set expire at 2020-10-26 17:57:15 +0000 UTC (2m55.90011535s from now)"
time="2020-10-26T17:54:19Z" level=info msg="Found Workflow sensor-workflow9b2m9 set expire at 2020-10-26 18:09:07 +0000 UTC (14m47.897681136s from now)"
time="2020-10-26T17:54:19Z" level=info msg="Found Workflow sensor-workflow6wgw2 set expire at 2020-10-26 18:00:54 +0000 UTC (6m34.893171668s from now)"
time="2020-10-26T17:57:15Z" level=info msg="Deleting TTL expired workflow sensor-workflowkg2mn"
time="2020-10-26T17:57:15Z" level=info msg="Found Workflow sensor-workflowkg2mn set expire at 2020-10-26 17:57:15 +0000 UTC (-27.24591ms from now)"
time="2020-10-26T17:57:17Z" level=info msg="Deleting TTL expired workflow sensor-workflow75p5w"
time="2020-10-26T17:57:17Z" level=info msg="Found Workflow sensor-workflow75p5w set expire at 2020-10-26 17:57:17 +0000 UTC (-20.316923ms from now)"
time="2020-10-26T17:59:07Z" level=info msg="Deleting TTL expired workflow sensor-workflowbdf4b"
time="2020-10-26T17:59:07Z" level=info msg="Found Workflow sensor-workflowbdf4b set expire at 2020-10-26 17:59:07 +0000 UTC (-25.88981ms from now)"
time="2020-10-26T17:59:07Z" level=info msg="Found Workflow sensor-workflowbdf4b set expire at 2020-10-26 17:59:07 +0000 UTC (-25.90771ms from now)"
time="2020-10-26T18:00:54Z" level=info msg="Deleting TTL expired workflow sensor-workflow6wgw2"
time="2020-10-26T18:00:54Z" level=info msg="Found Workflow sensor-workflow6wgw2 set expire at 2020-10-26 18:00:54 +0000 UTC (-21.316032ms from now)"
time="2020-10-26T18:00:55Z" level=info msg="Deleting TTL expired workflow sensor-workflow45mvg"
time="2020-10-26T18:00:55Z" level=info msg="Found Workflow sensor-workflow45mvg set expire at 2020-10-26 18:00:55 +0000 UTC (-21.750088ms from now)"
time="2020-10-26T18:09:07Z" level=info msg="Deleting TTL expired workflow sensor-workflow9b2m9"
time="2020-10-26T18:09:07Z" level=info msg="Found Workflow sensor-workflow9b2m9 set expire at 2020-10-26 18:09:07 +0000 UTC (-22.717329ms from now)"
time="2020-10-26T18:14:19Z" level=info msg="Found Workflow sensor-workflow976mx set expire at 2020-10-26 18:14:54 +0000 UTC (34.907076246s from now)"
time="2020-10-26T18:14:19Z" level=info msg="Found Workflow sensor-workflowtjxh9 set expire at 2020-10-26 18:14:50 +0000 UTC (30.893496113s from now)"
time="2020-10-26T18:14:50Z" level=info msg="Deleting TTL expired workflow sensor-workflowtjxh9"
time="2020-10-26T23:14:19Z" level=info msg="Found Workflow sensor-workflownjl79 set expire at 2020-10-26 22:00:53 +0000 UTC (-1h13m26.209453018s from now)"
time="2020-10-26T23:14:19Z" level=info msg="Found Workflow sensor-workflowb2cmg set expire at 2020-10-26 23:09:26 +0000 UTC (-4m53.222164421s from now)"
time="2020-10-26T23:14:49Z" level=info msg="Deleting TTL expired workflow sensor-workflowmxgsw"
time="2020-10-26T23:14:49Z" level=info msg="Found Workflow sensor-workflowmxgsw set expire at 2020-10-26 23:14:49 +0000 UTC (-29.400692ms from now)"
time="2020-10-27T01:54:19Z" level=info msg="Found Workflow sensor-workflowmcbt6 set expire at 2020-10-27 00:10:22 +0000 UTC (-1h43m57.095676904s from now)"
time="2020-10-27T01:54:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowmcbt6"
time="2020-10-27T01:54:19Z" level=info msg="Found Workflow sensor-workflowmcbt6 set expire at 2020-10-27 00:10:22 +0000 UTC (-1h43m57.116476128s from now)"
time="2020-10-27T03:14:19Z" level=info msg="Found Workflow sensor-workflow9vvp2 set expire at 2020-10-27 01:01:01 +0000 UTC (-2h13m18.102425145s from now)"
time="2020-10-27T03:14:19Z" level=info msg="Found Workflow sensor-workflowdhzgh set expire at 2020-10-27 03:32:04 +0000 UTC (17m44.89711477s from now)"
time="2020-10-27T03:14:19Z" level=info msg="Deleting TTL expired workflow sensor-workflow9vvp2"
time="2020-10-27T03:14:19Z" level=info msg="Found Workflow sensor-workflow9vvp2 set expire at 2020-10-27 01:01:01 +0000 UTC (-2h13m18.123677423s from now)"
time="2020-10-27T03:32:04Z" level=info msg="Deleting TTL expired workflow sensor-workflowdhzgh"
time="2020-10-27T03:32:04Z" level=info msg="Found Workflow sensor-workflowdhzgh set expire at 2020-10-27 03:32:04 +0000 UTC (-27.845074ms from now)"
time="2020-10-27T04:34:19Z" level=info msg="Found Workflow sensor-workflownvgg7 set expire at 2020-10-27 03:14:56 +0000 UTC (-1h19m23.103273413s from now)"
time="2020-10-27T04:34:19Z" level=info msg="Deleting TTL expired workflow sensor-workflow9bb7c"
time="2020-10-27T04:34:19Z" level=info msg="Found Workflow sensor-workflowlzfxp set expire at 2020-10-27 01:15:06 +0000 UTC (-3h19m13.103945825s from now)"
time="2020-10-27T07:14:19Z" level=info msg="Found Workflow sensor-workflowts75x set expire at 2020-10-27 06:00:54 +0000 UTC (-1h13m25.108062643s from now)"
time="2020-10-27T07:14:19Z" level=info msg="Found Workflow sensor-workflowjk7p7 set expire at 2020-10-27 05:01:09 +0000 UTC (-2h13m10.110830923s from now)"
time="2020-10-27T07:14:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowts75x"
time="2020-10-27T10:34:19Z" level=info msg="Found Workflow sensor-workflows6rff set expire at 2020-10-27 05:00:52 +0000 UTC (-5h33m27.393416928s from now)"
time="2020-10-27T10:34:19Z" level=info msg="Deleting TTL expired workflow sensor-workflowp4mxb"
time="2020-10-27T10:34:19Z" level=info msg="Found Workflow sensor-workflow6pnjr set expire at 2020-10-27 08:26:31 +0000 UTC (-2h7m48.404635784s from now)"
time="2020-10-27T10:34:19Z" level=info msg="Found Workflow sensor-workflowp4mxb set expire at 2020-10-27 07:15:46 +0000 UTC (-3h18m33.418426011s from now)"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2020-10-27 15:36
Is this a duplicate of #4246?

**Comment by sarabala1979** [comment] 2020-10-27 15:39
@alexecNo, this is a different issue. I will take a look.
@akonale  Can you provide your sample workflow or your `ttlStrategy`?

**Comment by akonale** [comment] 2020-10-27 15:46
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-10-27T15:00:00Z"
  generateName: sensor-workflow
  generation: 22
  name: name
  namespace: my-ns
  resourceVersion: "1375790286"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/my-ns/workflows/wf-inst
  uid: b80cbb44-4c3a-46ec-96e1-4e5a1fab99f9
spec:
  activeDeadlineSeconds: 7200
  arguments:
    parameters:
      - name: dateTime
        value: 2020-10-27 15:00:00.000124754 +0000 UTC m=+92217.581004853
  entrypoint: template-1
  serviceAccountName: argo
  templates:
    - arguments: {}
      dag:
        tasks:
          - arguments:
              parameters:
                - name: cmd
                  value: some_cmd
            name: task1
            template: ""
            templateRef:
              name: generic
              template: generic-action
      inputs: {}
      metadata: {}
      name: template-1
      outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 21600      
```

**Comment by sarabala1979** [comment] 2020-10-28 17:59
@akonale looks like ttlController is making a delete call but the workflow object is not getting deleted. 
https://github.com/argoproj/argo/pull/4133  will fix this issue.
can you provide us some old workflow spec which is ttlcluster deleted?
```
:19Z" level=info msg="Found Workflow sensor-workflowp4mxb set expire at 2020-10-27 07:15:46 +0000 UTC (-3h18m33.418426011s from now)"
```

**Comment by akonale** [comment] 2020-10-29 15:05
@sarabala1979 , we are running on vanilla k8s installation. And I did not quite get what you meant by `ttlcluster deleted`

**Comment by sarabala1979** [comment] 2020-10-29 15:41
it is ttl controller deleted workflow. I can see in above workflows overdue for deletion `(-3h18m33`. Are you seeing those workflows on your namespace which are deleted by TTL controller `time="2020-10-26T18:14:50Z" level=info msg="Deleting TTL expired workflow **sensor-workflowtjxh9**"`?

**Comment by sarabala1979** [comment] 2020-12-10 19:35
No Response from the user. Closing.

**Closed by sarabala1979** 2020-12-10 19:35 UTC
Labels: bug, epic/reliability
