### ISSUE TITLE
loops-param-result.yaml: failed to process 1000 pods job.

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#505] opened 2017-11-30 23:30 UTC
Testing argo 2.0 by submiting  loops-param-result.yaml with 1000 pods, it stop processing jobs after about 1 hour. 

Here is controller logs for this:
```
Francis-Macbook-Pro:examples francis$ kubectl logs workflow-controller-856bc99c-2jm8w --namespace kube-system  --tail 30
time="2017-11-30T22:25:02Z" level=info msg="Evaluating node loops-param-result-pg6df[1].sleep(995): template: sleep-n-sec" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Node loops-param-result-pg6df[1].sleep(995) already completed" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Evaluating node loops-param-result-pg6df[1].sleep(996): template: sleep-n-sec" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Node loops-param-result-pg6df[1].sleep(996) already completed" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Evaluating node loops-param-result-pg6df[1].sleep(997): template: sleep-n-sec" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Node loops-param-result-pg6df[1].sleep(997) already completed" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Evaluating node loops-param-result-pg6df[1].sleep(998): template: sleep-n-sec" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Node loops-param-result-pg6df[1].sleep(998) already completed" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Evaluating node loops-param-result-pg6df[1].sleep(999): template: sleep-n-sec" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Node loops-param-result-pg6df[1].sleep(999) already completed" namespace=default workflow=loops-param-result-pg6df
time="2017-11-30T22:25:02Z" level=info msg="Workflow step group node loops-param-result-pg6df[1] (loops-param-result-pg6df-3781070587) not yet completed" namespace=default workflow=loops-param-result-pg6df
ERROR: logging before flag.Parse: W1130 22:27:33.509272       1 reflector.go:334] github.com/argoproj/argo/workflow/controller/controller.go:280: watch of *v1.Pod ended with: too old resource version: 338199 (346268)
time="2017-11-30T23:06:12Z" level=info msg="Processing wf: /apis/argoproj.io/v1/namespaces/default/workflows/loops-param-result-42k8k"
time="2017-11-30T23:06:12Z" level=info msg="Evaluating node loops-param-result-42k8k: template: loop-param-result-example" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Initialized workflow node loops-param-result-42k8k (loops-param-result-42k8k)" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Initializing step group node loops-param-result-42k8k[0] (loops-param-result-42k8k-3777168805)" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Evaluating node loops-param-result-42k8k[0].generate: template: gen-number-list" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Creating Pod: loops-param-result-42k8k[0].generate" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Created pod: loops-param-result-42k8k-3826488430" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Initialized container node loops-param-result-42k8k[0].generate (loops-param-result-42k8k-3826488430)" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Workflow step group node loops-param-result-42k8k[0] (loops-param-result-42k8k-3777168805) not yet completed" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Workflow /apis/argoproj.io/v1/namespaces/default/workflows/loops-param-result-42k8k updated" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Processing wf: /apis/argoproj.io/v1/namespaces/default/workflows/loops-param-result-42k8k"
time="2017-11-30T23:06:12Z" level=info msg="Evaluating node loops-param-result-42k8k: template: loop-param-result-example" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Evaluating node loops-param-result-42k8k[0].generate: template: gen-number-list" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Creating Pod: loops-param-result-42k8k[0].generate" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="pod loops-param-result-42k8k[0].generate already exists" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Initialized container node loops-param-result-42k8k[0].generate (loops-param-result-42k8k-3826488430)" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Workflow step group node loops-param-result-42k8k[0] (loops-param-result-42k8k-3777168805) not yet completed" namespace=default workflow=loops-param-result-42k8k
time="2017-11-30T23:06:12Z" level=info msg="Workflow /apis/argoproj.io/v1/namespaces/default/workflows/loops-param-result-42k8k updated" namespace=default workflow=loops-param-result-42k8k
```

**Comment by jessesuen** [comment] 2017-12-01 09:52
What was observed was the controller had transitioned the container node into a `Running` state. This only happens when we get a successful return back from K8s API Server during pod creation. Yet somehow this pod was missing when I attempted to look at the pod via `kubectl get pod <nodename>`

@francis-ax - by any chance did you delete any pods manually? I believe that this could happen if a pod gets deleted from underneath the controller.

**Comment by francis-ax** [comment] 2017-12-01 22:16
I didn't delete any pods manually.
I just try again with 800 pods and hit the same error. again 
```
"ERROR: logging before flag.Parse: W1201 22:04:52.193866       1 reflector.go:334] github.com/argoproj/argo/workflow/controller/controller.go:280: watch of *v1.Pod ended with: too old resource version: 543982 (544231)"
```

```
time="2017-12-01T22:04:09Z" level=info msg="Evaluating node loops-param-result-brz27[1].sleep(796): template: sleep-n-sec" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Node loops-param-result-brz27[1].sleep(796) already completed" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Evaluating node loops-param-result-brz27[1].sleep(797): template: sleep-n-sec" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Node loops-param-result-brz27[1].sleep(797) already completed" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Evaluating node loops-param-result-brz27[1].sleep(798): template: sleep-n-sec" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Node loops-param-result-brz27[1].sleep(798) already completed" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Evaluating node loops-param-result-brz27[1].sleep(799): template: sleep-n-sec" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Node loops-param-result-brz27[1].sleep(799) already completed" namespace=default workflow=loops-param-result-brz27
time="2017-12-01T22:04:09Z" level=info msg="Workflow step group node loops-param-result-brz27[1] (loops-param-result-brz27-3135910117) not yet completed" namespace=default workflow=loops-param-result-brz27
ERROR: logging before flag.Parse: W1201 22:04:52.193866       1 reflector.go:334] github.com/argoproj/argo/workflow/controller/controller.go:280: watch of *v1.Pod ended with: too old resource version: 543982 (544231)
Francis-Macbook-Pro:src francis$
```

**Comment by jessesuen** [comment] 2017-12-04 02:53
I am able to reproduce this and see the issue happen live. The controller somehow gets wedged and suddenly stops seeing pod/workflow updates, despite the fact that pods are changing state, and I went and manually edited a workflow without seeing activity in the controller logs. I will be instrumenting the controller so that we can get on-demand tracebacks through signaling to debug what it is doing when it gets into this state.

**Closed** 2017-12-04 10:42 UTC
Labels: bug

**Comment by jessesuen** [comment] 2017-12-04 12:34
Reproduced after recent improvements. 
```
ERROR: logging before flag.Parse: W1204 11:52:39.728574       1 reflector.go:334] github.com/argoproj/argo/workflow/controller/controller.go:354: watch of *v1.Pod ended with: too old resource version: 171879 (173704)
```
Here is the backtrace at that point in time:
```
goroutine 36 [semacquire, 27 minutes]:
sync.runtime_Semacquire(0xc4203079cc)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4203079c0)
	/usr/local/go/src/sync/waitgroup.go:131 +0x72
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Wait(0xc4203079c0)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:47 +0x2d
panic(0x102bde0, 0xc42360a340)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x102bde0, 0xc42360a340)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/argoproj/argo/workflow/controller.(*WorkflowController).watchWorkflowPods.func3(0x1065aa0, 0xc4230c96e0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:350 +0x77
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(0xc420310ab0, 0xc420310ac0, 0xc420310ad0, 0x1065aa0, 0xc4230c96e0)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache/controller.go:209 +0x49
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnDelete(0xc42018ed80, 0x1065aa0, 0xc4230c96e0)
	<autogenerated>:1 +0x62
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x1033980, 0xc4227a61a0, 0x1033980, 0xc4227a61a0)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache/controller.go:320 +0x38c
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc4203b3a40, 0xc4201ca960, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 +0x268
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc420283900)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x40
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2a
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42003bfb0)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4209d5fb0, 0x3b9aca00, 0x0, 0xc42003bf01, 0xc420064240)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42003bfb0, 0x3b9aca00, 0xc420064240)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc420283900, 0xc420064240)
	/root/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2b7
created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).watchWorkflowPods
	/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:354 +0x231
```


```
			DeleteFunc: func(obj interface{}) {
				pod := obj.(*apiv1.Pod)
				wfc.podUpdates <- pod
			},
```
Looks like the type assertion needs to be guarded.
