### ISSUE TITLE
Interfaced Argo API / K8s API workflow client library

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1980] opened 2020-01-15 02:56 UTC
# Summary

The CLI code is **not** DRY. I see the following all over the place:

```golang
if client.ArgoServer != "" {
   // do something
} else {
   // do something else which is nearly copied and pasted from above
}
```

This really is an indication that the client needs to be interfaced and abstracted away from the CLI code

# Motivation

There is a lot of repeated code, which is unmaintainable.
Consumers will be able to benefit from a client library which can interact with either K8s or Argo API interchangeably.

# Proposal

Create a Argo Client Interface which can switch between the K8s API and the Argo API server interchangeably. Modify the CLI code to leverage the new client.

**Comment by alexec** [comment] 2020-01-29 18:44
Duplicate of #1951.

**Closed by alexec** 2020-01-29 18:44 UTC
Labels: argo-client, duplicate, enhancement
