### ISSUE TITLE
Workflow marked as failed; but looks like all steps succeeded on retry

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#903] opened 2018-07-06 17:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
Workflow is marked as failed but as far as I can tell all the steps completed on retry so I would expect
the workflow to marked as success

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
No way to reproduce

**Anything else we need to know?**:

Attaching an image showing the workflow from the UI
![failed_workflow](https://user-images.githubusercontent.com/777219/42393014-baeba274-8109-11e8-9b4b-fef35f30910f.png)

Attaching the output of describe workflow
[wf.txt](https://github.com/argoproj/argo/files/2171474/wf.txt)

**Environment**:
- Argo version:
argoproj/workflow-controller:v2.1.0

- Kubernetes version :
```
$ kubectl version -o yaml
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment] 2018-07-07 06:32
v2.1.1 fixes some metadata issues that caused issues with the DAG presentation of the workflow, so it's hard to tell from the UI what went wrong. 

Instead of `kubectl describe wf`, could you send the output of: `argo get <workflowname>` and `kubectl get <workflowname> -o yaml` instead?  From those I can probably tell what went wrong.

**Comment by jlewi** [comment] 2018-07-07 19:51
Thanks for investigating
Here's the output
[wf.yaml.txt](https://github.com/argoproj/argo/files/2173043/wf.yaml.txt)
[wf.argo.txt](https://github.com/argoproj/argo/files/2173047/wf.argo.txt)

**Comment by jessesuen** [comment] 2018-08-01 09:09
Determined that retries with DAGs was not working properly. Dupe of https://github.com/argoproj/argo/issues/885 and is fixed in tip.

**Closed** 2018-08-01 09:09 UTC
Labels: duplicate
