### ISSUE TITLE
inconsistent behavior of parallel workflow step execution

### ISSUE THREAD

**Issue by mhehle** [argoproj/argo#4466] opened 2020-11-05 13:36 UTC
## Summary 
Argo Workflows executes DAG/Steps in different ways.

- Workflow with DAG and Image1 is executed in parallel,  
- Workflow with DAG and Image2 is execute sequentially 

**What happened/what you expected to happen?**
Both workflows should execute DAG/steps in parallel.

## Diagnostics

**What Kubernetes provider are you using?** 
v1.19.3 > local setup with docker desktop version 2.5.0.0 (49427)

**What version of Argo Workflows are you running?** 
v2.11.7

**Workflow 1 -- parallel execution working**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:

  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
```
**Workflow 2 -- parallel execution not working**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:

  - name: diamond
    dag:
      tasks:
      - name: A
        template: whalesay
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: whalesay
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: whalesay
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: whalesay
        arguments:
          parameters: [{name: message, value: D}]

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

**Log Workflow 2**
```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2020-11-05T13:24:25Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:25Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:25Z" level=info msg="DAG node dag-diamond-66j84 initialized Running" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:25Z" level=info msg="All of node dag-diamond-66j84.A dependencies [] completed" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:25Z" level=info msg="Pod node dag-diamond-66j84-1264239868 initialized Pending" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:25Z" level=info msg="Created pod: dag-diamond-66j84.A (dag-diamond-66j84-1264239868)" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:25Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771343 workflow=dag-diamond-66j84
time="2020-11-05T13:24:26Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:26Z" level=info msg="Updating node dag-diamond-66j84-1264239868 message: ContainerCreating"
time="2020-11-05T13:24:26Z" level=info msg="Skipped pod dag-diamond-66j84.A (dag-diamond-66j84-1264239868) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:26Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771353 workflow=dag-diamond-66j84
time="2020-11-05T13:24:27Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:27Z" level=info msg="Skipped pod dag-diamond-66j84.A (dag-diamond-66j84-1264239868) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:29Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:29Z" level=info msg="Setting node dag-diamond-66j84-1264239868 outputs"
time="2020-11-05T13:24:29Z" level=info msg="Updating node dag-diamond-66j84-1264239868 status Pending -> Running"
time="2020-11-05T13:24:29Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771366 workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Updating node dag-diamond-66j84-1264239868 status Running -> Succeeded"
time="2020-11-05T13:24:30Z" level=info msg="All of node dag-diamond-66j84.B dependencies [A] completed" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Pod node dag-diamond-66j84-1314572725 initialized Pending" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Created pod: dag-diamond-66j84.B (dag-diamond-66j84-1314572725)" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="All of node dag-diamond-66j84.C dependencies [A] completed" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Pod node dag-diamond-66j84-1297795106 initialized Pending" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Created pod: dag-diamond-66j84.C (dag-diamond-66j84-1297795106)" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:30Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771377 workflow=dag-diamond-66j84
time="2020-11-05T13:24:31Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:31Z" level=info msg="Updating node dag-diamond-66j84-1314572725 message: ContainerCreating"
time="2020-11-05T13:24:31Z" level=info msg="Updating node dag-diamond-66j84-1297795106 message: ContainerCreating"
time="2020-11-05T13:24:31Z" level=info msg="Skipped pod dag-diamond-66j84.B (dag-diamond-66j84-1314572725) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:31Z" level=info msg="Skipped pod dag-diamond-66j84.C (dag-diamond-66j84-1297795106) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:31Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1264239868
time="2020-11-05T13:24:31Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771391 workflow=dag-diamond-66j84
time="2020-11-05T13:24:32Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:32Z" level=info msg="Skipped pod dag-diamond-66j84.B (dag-diamond-66j84-1314572725) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:32Z" level=info msg="Skipped pod dag-diamond-66j84.C (dag-diamond-66j84-1297795106) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:32Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1264239868
time="2020-11-05T13:24:34Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:34Z" level=info msg="Setting node dag-diamond-66j84-1314572725 outputs"
time="2020-11-05T13:24:34Z" level=info msg="Updating node dag-diamond-66j84-1314572725 status Pending -> Running"
time="2020-11-05T13:24:34Z" level=info msg="Skipped pod dag-diamond-66j84.C (dag-diamond-66j84-1297795106) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:35Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771404 workflow=dag-diamond-66j84
time="2020-11-05T13:24:36Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:36Z" level=info msg="Updating node dag-diamond-66j84-1314572725 status Running -> Succeeded"
time="2020-11-05T13:24:36Z" level=info msg="Setting node dag-diamond-66j84-1297795106 outputs"
time="2020-11-05T13:24:36Z" level=info msg="Updating node dag-diamond-66j84-1297795106 status Pending -> Running"
time="2020-11-05T13:24:36Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771412 workflow=dag-diamond-66j84
time="2020-11-05T13:24:37Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:37Z" level=info msg="Updating node dag-diamond-66j84-1297795106 status Running -> Succeeded"
time="2020-11-05T13:24:37Z" level=info msg="All of node dag-diamond-66j84.D dependencies [B C] completed" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:37Z" level=info msg="Pod node dag-diamond-66j84-1213907011 initialized Pending" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:37Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1314572725
time="2020-11-05T13:24:37Z" level=info msg="Created pod: dag-diamond-66j84.D (dag-diamond-66j84-1213907011)" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:37Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771420 workflow=dag-diamond-66j84
time="2020-11-05T13:24:38Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:38Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1314572725
time="2020-11-05T13:24:38Z" level=info msg="Updating node dag-diamond-66j84-1213907011 message: ContainerCreating"
time="2020-11-05T13:24:38Z" level=info msg="Skipped pod dag-diamond-66j84.D (dag-diamond-66j84-1213907011) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:38Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1297795106
time="2020-11-05T13:24:38Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771429 workflow=dag-diamond-66j84
time="2020-11-05T13:24:39Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:39Z" level=info msg="Skipped pod dag-diamond-66j84.D (dag-diamond-66j84-1213907011) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-66j84
time="2020-11-05T13:24:39Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1297795106
time="2020-11-05T13:24:41Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:41Z" level=info msg="Setting node dag-diamond-66j84-1213907011 outputs"
time="2020-11-05T13:24:41Z" level=info msg="Updating node dag-diamond-66j84-1213907011 status Pending -> Running"
time="2020-11-05T13:24:41Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771440 workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Updating node dag-diamond-66j84-1213907011 status Running -> Succeeded"
time="2020-11-05T13:24:42Z" level=info msg="Outbound nodes of dag-diamond-66j84 set to [dag-diamond-66j84-1213907011]" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="node dag-diamond-66j84 phase Running -> Succeeded" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="node dag-diamond-66j84 finished: 2020-11-05 13:24:42.2407557 +0000 UTC" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Checking daemoned children of dag-diamond-66j84" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Marking workflow completed" namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Checking daemoned children of " namespace=argo workflow=dag-diamond-66j84
time="2020-11-05T13:24:42Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=771447 workflow=dag-diamond-66j84
time="2020-11-05T13:24:43Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-66j84-1213907011
```
**Log Workflow 1**
```
time="2020-11-05T13:26:04Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:04Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:04Z" level=info msg="DAG node dag-diamond-wx7xr initialized Running" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:04Z" level=info msg="All of node dag-diamond-wx7xr.A dependencies [] completed" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:04Z" level=info msg="Pod node dag-diamond-wx7xr-990764344 initialized Pending" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:04Z" level=info msg="Created pod: dag-diamond-wx7xr.A (dag-diamond-wx7xr-990764344)" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:04Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771593 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:05Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:05Z" level=info msg="Updating node dag-diamond-wx7xr-990764344 message: ContainerCreating"
time="2020-11-05T13:26:05Z" level=info msg="Skipped pod dag-diamond-wx7xr.A (dag-diamond-wx7xr-990764344) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:05Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771605 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:06Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:06Z" level=info msg="Setting node dag-diamond-wx7xr-990764344 outputs"
time="2020-11-05T13:26:06Z" level=info msg="Updating node dag-diamond-wx7xr-990764344 status Pending -> Running"
time="2020-11-05T13:26:06Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771609 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Updating node dag-diamond-wx7xr-990764344 status Running -> Succeeded"
time="2020-11-05T13:26:07Z" level=info msg="All of node dag-diamond-wx7xr.B dependencies [A] completed" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Pod node dag-diamond-wx7xr-1041097201 initialized Pending" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Created pod: dag-diamond-wx7xr.B (dag-diamond-wx7xr-1041097201)" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="All of node dag-diamond-wx7xr.C dependencies [A] completed" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Pod node dag-diamond-wx7xr-1024319582 initialized Pending" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Created pod: dag-diamond-wx7xr.C (dag-diamond-wx7xr-1024319582)" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:07Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771621 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:08Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:08Z" level=info msg="Updating node dag-diamond-wx7xr-1041097201 message: ContainerCreating"
time="2020-11-05T13:26:08Z" level=info msg="Updating node dag-diamond-wx7xr-1024319582 message: ContainerCreating"
time="2020-11-05T13:26:08Z" level=info msg="Skipped pod dag-diamond-wx7xr.C (dag-diamond-wx7xr-1024319582) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:08Z" level=info msg="Skipped pod dag-diamond-wx7xr.B (dag-diamond-wx7xr-1041097201) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:08Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-990764344
time="2020-11-05T13:26:08Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771635 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:09Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:09Z" level=info msg="Setting node dag-diamond-wx7xr-1041097201 outputs"
time="2020-11-05T13:26:09Z" level=info msg="Updating node dag-diamond-wx7xr-1041097201 status Pending -> Running"
time="2020-11-05T13:26:09Z" level=info msg="Setting node dag-diamond-wx7xr-1024319582 outputs"
time="2020-11-05T13:26:09Z" level=info msg="Updating node dag-diamond-wx7xr-1024319582 status Pending -> Running"
time="2020-11-05T13:26:09Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-990764344
time="2020-11-05T13:26:09Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771645 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:10Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:10Z" level=info msg="Updating node dag-diamond-wx7xr-1041097201 status Running -> Succeeded"
time="2020-11-05T13:26:10Z" level=info msg="Updating node dag-diamond-wx7xr-1024319582 status Running -> Succeeded"
time="2020-11-05T13:26:10Z" level=info msg="All of node dag-diamond-wx7xr.D dependencies [B C] completed" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:10Z" level=info msg="Pod node dag-diamond-wx7xr-1074652439 initialized Pending" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:10Z" level=info msg="Created pod: dag-diamond-wx7xr.D (dag-diamond-wx7xr-1074652439)" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:10Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771654 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:11Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:11Z" level=info msg="Updating node dag-diamond-wx7xr-1074652439 message: ContainerCreating"
time="2020-11-05T13:26:11Z" level=info msg="Skipped pod dag-diamond-wx7xr.D (dag-diamond-wx7xr-1074652439) creation: already exists" namespace=argo podPhase=Pending workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:11Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-1041097201
time="2020-11-05T13:26:11Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-1024319582
time="2020-11-05T13:26:11Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771667 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:12Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:12Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-1024319582
time="2020-11-05T13:26:12Z" level=info msg="Setting node dag-diamond-wx7xr-1074652439 outputs"
time="2020-11-05T13:26:12Z" level=info msg="Updating node dag-diamond-wx7xr-1074652439 status Pending -> Running"
time="2020-11-05T13:26:12Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-1041097201
time="2020-11-05T13:26:12Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=771670 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Processing workflow" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Updating node dag-diamond-wx7xr-1074652439 status Running -> Succeeded"
time="2020-11-05T13:26:13Z" level=info msg="Outbound nodes of dag-diamond-wx7xr set to [dag-diamond-wx7xr-1074652439]" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="node dag-diamond-wx7xr phase Running -> Succeeded" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="node dag-diamond-wx7xr finished: 2020-11-05 13:26:13.1947219 +0000 UTC" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Checking daemoned children of dag-diamond-wx7xr" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Marking workflow completed" namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Checking daemoned children of " namespace=argo workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:13Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=771678 workflow=dag-diamond-wx7xr
time="2020-11-05T13:26:14Z" level=info msg="Labeled pod completed" namespace=argo pod=dag-diamond-wx7xr-1074652439
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment] 2020-11-05 14:40
Will investigate

**Comment by simster7** [comment] 2020-11-09 16:43
I am not able to reproduce this. Does this issue happen reliably? Could it have something to do with your environment?

**Comment by mhehle** [comment] 2020-11-10 09:36
> I am not able to reproduce this. Does this issue happen reliably? Could it have something to do with your environment?

Yes this issue happens reliably. 

I made a small video and uploaded it on YT. 
-> https://youtu.be/79GP5QYWdIs

**I installed and started argo with following commands:**

```shell
kubectl create ns argo

kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/namespace-install.yaml

kubectl -n argo port-forward deployment/argo-server 2746:2746
```

**Comment by simster7** [comment] 2020-11-10 14:53
I see what you're saying now.

However, even from your video it looks like Argo is working correctly. When you see the two yellow `Pending` nodes on the workflow, that means that Argo has scheduled both Pods to run and from your video it's clear that it does so in parallel. What happens after Argo creates the Pods is entirely in K8s' (and not in Argo's) control. The small delay between the two Pods starting could be explained by issues related to K8s, such as the `whalesay` container needing more resources, or some scheduling kinks with K8s.

As a test, I ran the same "Not Working" workflow, but instead of simply running the `cowsay` command, I ran `sleep 10`. You can see in the following that although one Pod takes longer to start, both are indeed running in parallel:

https://share.getcloudapp.com/geuqGQRv

I'll be closing this as a non-issue, but if you believe I've overlooked something please let me know and I can reopen.

**Closed by simster7** 2020-11-10 14:53 UTC
Labels: bug, works-for-me
