### ISSUE TITLE
Argo cli doesn't support numeric workflow output parameters

### ISSUE THREAD

**Issue by idsvandermolen** [argoproj/argo#4141] opened 2020-09-28 11:25 UTC
## Summary 
Argo client doesn't correctly handle numeric workflow output parameters. Instead it exits with an error like:
```
FATA[0002] an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.Workflow.Status: v1alpha1.WorkflowStatus.Nodes: v1alpha1.NodeStatus.Outputs: v1alpha1.Outputs.Parameters: []v1alpha1.Parameter: v1alpha1.Parameter.Value: ReadString: expects \" or n, but found 1, error found in #10 byte of ...|,\"value\":1234,\"value|..., bigger context ...|s\":[{\"globalName\":\"my_id\",\"name\":\"my_id\",\"value\":1234,\"valueFrom\":{\"path\":\"/tmp/my_id\"}}]},\"phase\":\"|...") has prevented the request from succeeding 
```
or 
```
FATA[0000] v1alpha1.Workflow.Status: v1alpha1.WorkflowStatus.Nodes: v1alpha1.NodeStatus.Outputs: v1alpha1.Outputs.Parameters: []v1alpha1.Parameter: v1alpha1.Parameter.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":1234,"value|..., bigger context ...|s":[{"globalName":"my_id","name":"my_id","value":1234,"valueFrom":{"path":"/tmp/my_id"}}]},"phase":"|... 
```

What happened/what you expected to happen?
argo client should show workflow parameters even if they are numeric. Instead it exits with an error
## Diagnostics
Submit a workflow like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: boom-
spec:
  entrypoint: main
  templates:
    - name: hello
      outputs:
        parameters:
          - name: my_id
            valueFrom:
              path: /tmp/my_id
            globalName: my_id # available through {{ workflow.outputs.parameters.my_id }}
      container:
        image: busybox:latest
        command:
          - /bin/sh
          - -c
          - |
            echo 1234 > /tmp/my_id

    - name: main
      dag:
        tasks:
          - name: hello
            template: hello
```
outputs:
```bash
argo submit --watch boom.yaml
Name:                boom-fpcxf
Namespace:           redacted
ServiceAccount:      redacted
Status:              Running
Created:             Mon Sep 28 13:10:00 +0200 (2 seconds ago)
Started:             Mon Sep 28 13:10:00 +0200 (2 seconds ago)
Duration:            2 seconds

STEP           TEMPLATE  PODNAME                DURATION  MESSAGE
 ● boom-fpcxf  main                                                          
 └-◷ hello     hello     boom-fpcxf-3733798180  2s        ContainerCreating  
FATA[0002] an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.Workflow.Status: v1alpha1.WorkflowStatus.Nodes: v1alpha1.NodeStatus.Outputs: v1alpha1.Outputs.Parameters: []v1alpha1.Parameter: v1alpha1.Parameter.Value: ReadString: expects \" or n, but found 1, error found in #10 byte of ...|,\"value\":1234,\"value|..., bigger context ...|s\":[{\"globalName\":\"my_id\",\"name\":\"my_id\",\"value\":1234,\"valueFrom\":{\"path\":\"/tmp/my_id\"}}]},\"phase\":\"|...") has prevented the request from succeeding 

argo get boom-fpcxf
FATA[0000] v1alpha1.Workflow.Status: v1alpha1.WorkflowStatus.Nodes: v1alpha1.NodeStatus.Outputs: v1alpha1.Outputs.Parameters: []v1alpha1.Parameter: v1alpha1.Parameter.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":1234,"value|..., bigger context ...|s":[{"globalName":"my_id","name":"my_id","value":1234,"valueFrom":{"path":"/tmp/my_id"}}]},"phase":"|... 

kubectl get wf boom-fpcxf
NAME         STATUS      AGE
boom-fpcxf   Succeeded   58s
```
What version of Argo Workflows are you running?
```
argo version
argo: latest+f8e750d.dirty
  BuildDate: 2020-09-17T22:11:28Z
  GitCommit: f8e750de5ebab6f3c494c972889b31ef24c73c9b
  GitTreeState: dirty
  GitTag: v2.11.0
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
```
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-28T11:10:00Z"
  generateName: boom-
  generation: 5
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
  name: boom-fpcxf
  namespace: redacted
  resourceVersion: "243265706"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/redacted/workflows/boom-fpcxf
  uid: f3627945-27f3-4191-a2f7-306722a7de52
spec:
  arguments: {}
  entrypoint: main
  serviceAccountName: redacted
  templates:
  - arguments: {}
    container:
      command:
      - /bin/sh
      - -c
      - |
        echo 1234 > /tmp/my_id
      image: busybox:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: hello
    outputs:
      parameters:
      - globalName: my_id
        name: my_id
        valueFrom:
          path: /tmp/my_id
  - arguments: {}
    dag:
      tasks:
      - arguments: {}
        name: hello
        template: hello
    inputs: {}
    metadata: {}
    name: main
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-09-28T11:10:03Z"
  nodes:
    boom-fpcxf:
      children:
      - boom-fpcxf-3733798180
      displayName: boom-fpcxf
      finishedAt: "2020-09-28T11:10:03Z"
      id: boom-fpcxf
      name: boom-fpcxf
      outboundNodes:
      - boom-fpcxf-3733798180
      phase: Succeeded
      startedAt: "2020-09-28T11:10:00Z"
      templateName: main
      templateScope: local/boom-fpcxf
      type: DAG
    boom-fpcxf-3733798180:
      boundaryID: boom-fpcxf
      displayName: hello
      finishedAt: "2020-09-28T11:10:02Z"
      hostNodeName: redacted
      id: boom-fpcxf-3733798180
      name: boom-fpcxf.hello
      outputs:
        exitCode: "0"
        parameters:
        - globalName: my_id
          name: my_id
          value: 1234
          valueFrom:
            path: /tmp/my_id
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-28T11:10:00Z"
      templateName: hello
      templateScope: local/boom-fpcxf
      type: Pod
  outputs:
    parameters:
    - name: my_id
      value: 1234
  phase: Succeeded
  resourcesDuration:
    cpu: 1
    memory: 1
  startedAt: "2020-09-28T11:10:00Z"
```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```
time="2020-09-28T11:06:28Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:28Z" level=info msg="Updated phase  -> Running" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:28Z" level=info msg="DAG node boom-2nwtf initialized Running" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:28Z" level=info msg="All of node boom-2nwtf.hello dependencies [] completed" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:28Z" level=info msg="Pod node boom-2nwtf-561381942 initialized Pending" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:28Z" level=info msg="Created pod: boom-2nwtf.hello (boom-2nwtf-561381942)" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:28Z" level=info msg="Workflow update successful" namespace=redacted phase=Running resourceVersion=243264446 workflow=boom-2nwtf
time="2020-09-28T11:06:29Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:29Z" level=info msg="Updating node boom-2nwtf-561381942 message: ContainerCreating"
time="2020-09-28T11:06:29Z" level=info msg="Skipped pod boom-2nwtf.hello (boom-2nwtf-561381942) creation: already exists" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:29Z" level=info msg="Workflow update successful" namespace=redacted phase=Running resourceVersion=243264452 workflow=boom-2nwtf
time="2020-09-28T11:06:30Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:31Z" level=info msg="Skipped pod boom-2nwtf.hello (boom-2nwtf-561381942) creation: already exists" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:32Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:32Z" level=info msg="Updating node boom-2nwtf-561381942 status Pending -> Running"
time="2020-09-28T11:06:32Z" level=info msg="Workflow update successful" namespace=redacted phase=Running resourceVersion=243264467 workflow=boom-2nwtf
time="2020-09-28T11:06:33Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Updating node boom-2nwtf-561381942 status Running -> Error"
time="2020-09-28T11:06:39Z" level=info msg="Updating node boom-2nwtf-561381942 message: failed to save outputs: Failed to establish pod watch: timed out waiting for the condition"
time="2020-09-28T11:06:39Z" level=info msg="Outbound nodes of boom-2nwtf set to [boom-2nwtf-561381942]" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="node boom-2nwtf phase Running -> Error" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="node boom-2nwtf finished: 2020-09-28 11:06:39.282091426 +0000 UTC" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Checking daemoned children of boom-2nwtf" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Updated phase Running -> Error" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Marking workflow completed" namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Checking daemoned children of " namespace=redacted workflow=boom-2nwtf
time="2020-09-28T11:06:39Z" level=info msg="Workflow update successful" namespace=redacted phase=Error resourceVersion=243264514 workflow=boom-2nwtf
time="2020-09-28T11:06:40Z" level=info msg="boom-2nwtf released all acquired locks"
time="2020-09-28T11:06:40Z" level=info msg="Labeled pod redacted/boom-2nwtf-561381942 completed"
time="2020-09-28T11:06:40Z" level=info msg="Workflow update successful" namespace=redacted phase=Error resourceVersion=243264514 workflow=boom-2nwtf
time="2020-09-28T11:06:41Z" level=info msg="Labeled pod redacted/boom-2nwtf-561381942 completed"
time="2020-09-28T11:10:00Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:00Z" level=info msg="Updated phase  -> Running" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:00Z" level=info msg="DAG node boom-fpcxf initialized Running" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:00Z" level=info msg="All of node boom-fpcxf.hello dependencies [] completed" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:00Z" level=info msg="Pod node boom-fpcxf-3733798180 initialized Pending" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:00Z" level=info msg="Created pod: boom-fpcxf.hello (boom-fpcxf-3733798180)" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:00Z" level=info msg="Workflow update successful" namespace=redacted phase=Running resourceVersion=243265676 workflow=boom-fpcxf
time="2020-09-28T11:10:01Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:01Z" level=info msg="Updating node boom-fpcxf-3733798180 message: ContainerCreating"
time="2020-09-28T11:10:01Z" level=info msg="Skipped pod boom-fpcxf.hello (boom-fpcxf-3733798180) creation: already exists" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:01Z" level=info msg="Workflow update successful" namespace=redacted phase=Running resourceVersion=243265687 workflow=boom-fpcxf
time="2020-09-28T11:10:02Z" level=info msg="insignificant pod change" key=redacted/boom-fpcxf-3733798180
time="2020-09-28T11:10:02Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:02Z" level=info msg="Setting node boom-fpcxf-3733798180 outputs"
time="2020-09-28T11:10:02Z" level=info msg="Updating node boom-fpcxf-3733798180 status Pending -> Running"
time="2020-09-28T11:10:02Z" level=info msg="setting workflow.outputs.parameters.my_id: '1234'" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:02Z" level=info msg="Workflow update successful" namespace=redacted phase=Running resourceVersion=243265695 workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Processing workflow" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Updating node boom-fpcxf-3733798180 status Running -> Succeeded"
time="2020-09-28T11:10:03Z" level=info msg="Outbound nodes of boom-fpcxf set to [boom-fpcxf-3733798180]" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="node boom-fpcxf phase Running -> Succeeded" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="node boom-fpcxf finished: 2020-09-28 11:10:03.955497743 +0000 UTC" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Checking daemoned children of boom-fpcxf" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Updated phase Running -> Succeeded" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Marking workflow completed" namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Checking daemoned children of " namespace=redacted workflow=boom-fpcxf
time="2020-09-28T11:10:03Z" level=info msg="Workflow update successful" namespace=redacted phase=Succeeded resourceVersion=243265706 workflow=boom-fpcxf
time="2020-09-28T11:10:04Z" level=info msg="boom-fpcxf released all acquired locks"
time="2020-09-28T11:10:04Z" level=info msg="Labeled pod redacted/boom-fpcxf-3733798180 completed"
time="2020-09-28T11:10:04Z" level=info msg="Workflow update successful" namespace=redacted phase=Succeeded resourceVersion=243265706 workflow=boom-fpcxf
time="2020-09-28T11:10:05Z" level=info msg="Labeled pod redacted/boom-fpcxf-3733798180 completed"
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment] 2020-09-28 14:44
This seems to be caused by https://github.com/argoproj/argo/pull/3963. However, I am so far unable to reproduce this on `v2.11.0` or on `master`. My suspicion is that you have a version mismatch between your controller and your `argo-server`. Can you check that you're both running on the same version?

**Comment by idsvandermolen** [comment] 2020-09-28 15:53
I think the controller and server in the cluster are running 2.10.1. The argo client is 2.11.0

**Comment by alexec** [comment] 2020-09-28 15:57
I don't think you can run v2.10 with v2.11 CLI. It will cause this issue. Can you please try with the v2.10.1 CLI?

**Comment by simster7** [comment] 2020-09-28 16:10
Closing. If having your CLI/controller/server all at the same version doesn't fix this issue, please feel free to comment again and reopen

**Closed by simster7** 2020-09-28 16:10 UTC
Labels: bug

**Comment by idsvandermolen** [comment] 2020-09-29 15:13
Upgrading k8s workloads to `2.11.0` indeed fixed the problem. I have to note however, that I did not expect a `2.11` client would have issues with a `2.10` server instance (semantic versioning / backwards compatibility etc 😂 )

**Comment by alexec** [comment] 2020-09-29 15:35
> Upgrading k8s workloads to `2.11.0` indeed fixed the problem. I have to note however, that I did not expect a `2.11` client would have issues with a `2.10` server instance (semantic versioning / backwards compatibility etc 😂 )

I think you are reasonable in this. We rarely see backwards compatibility issues like this. Is fact, is the only instance I can think of.
