### ISSUE TITLE
Unable to resolve artifact from one skipped step in another skipped step

### ISSUE THREAD

**Issue by jimdickinson** [argoproj/argo#1900] opened 2020-01-02 18:22 UTC
We have a fairly complex workflow that we pass some variables into so we can skip steps that aren't needed during this execution. When we do that, it would seem like artifact inputs/outputs are validated before the `when` clause that lets job steps get skipped over.

Here's a snippet that illustrates what's going on. The job fails at runtime before checking whether `use-magic-files` needs to run.

```yaml
    - - name: generating-basic-files
        template: generate-normal
    - - name: generating-magic-files
        when: "{{workflow.parameters.magicNeeded}} == true"
        template: generate-magic
    - - name: use-magic-files
        template: use-magic
        when: "{{workflow.parameters.magicNeeded}} == true"
        arguments:
          parameters:  
          - name: summary
            value: "{{steps.generating-magic-files.outputs.parameters.summary}}"
          artifacts:
          - name: details
            from: "{{steps.generating-magic-files.outputs.artifacts.details}}"
    - - name: generating-verbose-files
        template: generate-verbose
```

**Comment by alexec** [comment] 2020-01-03 01:42
Thank you for your bug report. Do you think you could please attach the whole workflow?

**Comment by gordiustechnologies** [comment] 2020-03-31 04:40
@alexec: We also ran into this problem. It happens not only with artifacts but also with output parameters. Here is a simple scenario to reproduce the issue: Consider two steps, say A and B, where B uses A's output. Assume that A and B have the same conditional execution expression (i.e. `when` expression). If this `when` expression evaluates to false, we get an error. We obviously shouldn't, since B is not going to execute either. As the OP points out, I think this is a simple evaluation order issue. @jimdickinson , do you have a workaround until we have a fix?

**Comment by ptemmer** [comment] 2020-04-23 10:30
+1

**Comment by dcd000** [comment] 2020-04-23 10:42
+1

**Comment by alexec** [comment] 2020-04-23 15:27
You should 👍 if you want to upvote an issue please. We use 👍 to prioritize would. That said, the fix is most likely needed in [operator.go](https://github.com/argoproj/argo/blob/master/workflow/controller/operator.go) if you have time to investigate.

**Comment by simster7** [comment] 2020-04-23 15:41
Is this not fixed by https://github.com/argoproj/argo/pull/2657? It should be in `2.7.5`

**Comment by sinvalmendes** [comment] 2020-05-05 11:12
We are using 2.7.6 and the this issue is still happening

**Comment by ozankabak** [comment] 2020-05-16 12:25
It is somewhat surprising that #2657 did not fix this.

**Closed** 2020-07-22 15:18 UTC
Labels: artifacts, bug, wontfix
