### ISSUE TITLE
Argo Cronworkflows reporting workflow status as ACTIVE even if workflow has completed

### ISSUE THREAD

**Issue by Sushant20** [argoproj/argo#4174] opened 2020-09-30 15:10 UTC
Team,
We have suddenly started getting issues with Argo cronworkflow scheduler hosted on EKS 1.17 where in jobs are unable to start as per schedule. Jobs seems to be working fine when manually triggered/submitted

We have observed 10X CPU spike for workflow controller pods during the issue window and could see below messages for all argo jobs in workflow controller pod logs:

`time="2020-09-29T00:00:00Z" level=info msg="job-********" has 'ConcurrencyPolicy: Forbid' and has an active Workflow so it was not run" namespace=******* workflow=job-*******`

Argo version is 2.9.5, installation has been done using quick start commands as mentioned here:
https://github.com/argoproj/argo/releases

In addition to below installation, we have also enabled workflow archiving feature to Postgres DB as mentioned here: https://argoproj.github.io/argo/workflow-archive/

Please note that we use one Argo for entire EKS cluster and argo jobs runs on multiple namespaces

Have we seen this type of issue/bug before and what could be possible cause?  
Is workflow archiving feature causing issue? I see multiple workflow archiving related patches/improvements in 2.11 version: https://github.com/argoproj/argo/releases

Please let me know, if you need more info on the issue.

**Comment by simster7** [comment] 2020-09-30 15:30
This has nothing to do with workflow archiving.

It seems like the CronWorkflow that is failing to run has `concurrencyPolicy: Forbid` set and has an active/Running Workflow in the cluster. Can you check if this is the case?

If not, can you provide a sample CronWorkflow that reproduces this issue?

Lastly, version 2.9.5 is now some months old. Consider upgrading to 2.11.1?

**Comment by Sushant20** [comment] 2020-10-01 16:42
@simster7 Thankyou for the prompt reply, we are currently not able to replicate the issue. 
Having said that we had to reinstall argo operator and redeploy all argo jobs to mitigate the issue as soon as possible. 

Here is sample(dummy) workflow yaml for reference:

`apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: job-****
  namespace: namespace-****
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: 1 * * * *
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  workflowMetadata:
    annotations:
      iam.amazonaws.com/role: ""
    creationTimestamp: null
    labels:
      job: job-****
  workflowSpec:
    arguments: {}
    entrypoint: job-dag
    onExit: exit-handler
    serviceAccountName: argosa
    templates:
    - arguments: {}
      inputs: {}
      metadata: {}
      name: exit-handler
      outputs: {}
      steps:
      - - arguments: {}
          name: oncall
          template: notify-oncall
          when: '{{workflow.status}} != Succeeded'
    - arguments: {}
      container:
        args:
        - oncall
        command:
        - python
        image: image-****:latest
        imagePullPolicy: Always
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: notify-oncall
      outputs: {}
    - arguments: {}
      dag:
        tasks:
        - arguments: {}
          name: stage-****
          template: stage-****
      inputs: {}
      metadata: {}
      name: job-dag
      outputs: {}
    - arguments: {}
      inputs: {}
      metadata: {}
      name: stage-****
      outputs: {}
      resource:
        action: create
        failureCondition: status.applicationState.state = FAILED
        manifest: |-
          apiVersion: sparkoperator.k8s.io/v1beta2
          kind: SparkApplication
          metadata:
            generateName: "stage-****-"
            namespace: "namespace-****"
            labels:
              job: "job-****"
              stage: "stage-****"
          spec:
            type: Scala
            mode: cluster
            sparkVersion: "2.4.5"
            image: "image-****:latest"
            imagePullPolicy: Always
            mainClass: "com.spark.****"
            mainApplicationFile: "local:///opt/spark/jars/spark-****.jar"
            arguments: ['namespaceName=namespace-****']
            restartPolicy:
              type: "Never"
            driver:
              cores: 1
              memory: "1024m"
              labels:
                version: "2.4.5"
                job: "job-****"
                stage: "stage-****"
              annotations:
                iam.amazonaws.com/role: iam-role-***
              serviceAccount: "sparksa"
            executor:
              cores: 1
              instances: 2
              memory: "2048m"
              labels:
                version: "2.4.5"
              annotations:
                iam.amazonaws.com/role: iam-role-***
        successCondition: status.applicationState.state = COMPLETED
`
I could also see similar issue being reported couple of hrs back: https://github.com/argoproj/argo/issues/4181

Would upgrading to 2.11.1 help? If yes, could this be breaking change?

Please note that concurrency:forbid is intended in my case because I don't want workflow to run if already workflow is active. Having said that, for us the workflow was actually completed but Argo workflow was reporting status as Active, which is pretty weird

**Comment by simster7** [comment] 2020-10-01 16:54
I will close this as a duplicate of #4181, feel free to continue the discussion there

**Closed by simster7** 2020-10-01 16:54 UTC
Labels: question
