### ISSUE TITLE
auth-mode server fails when Authorization header is passed.

### ISSUE THREAD

**Issue by tcolgate** [argoproj/argo#4400] opened 2020-10-27 17:36 UTC
## Summary 

We have argo server behind a reverse proxy that does github SSO.. Upgrading from argo 2.8 to 2.11, using `--auth-mode server` broke the UI. /api/v1/version was returned
```json
{"code":16,"message":"no valid authentication methods found for mode client"}
```
## Diagnostics
The error is caused because our reverse proxy adds an authorization header.

To recreate:
- run argo server with auth-mode server
- port-forward to argo-ui
- This works `curl http://localhost:2746/api/v1/version`
- This fails `curl -H "Authorization: Bearer 1234"  http://localhost:2746/api/v1/version`

This was tracked down to:
https://github.com/argoproj/argo/blob/f9b65c52321d6e49d7fbc78f69d18e7d1ee442ad/server/auth/gatekeeper.go#L117-L118

when only auth-mode server is active, authorization and cookie headers should be ignored.

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 

2.11.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment] 2020-10-27 17:54
Why are you sending a header?

**Comment by sarabala1979** [comment] 2020-10-27 18:57
@tcolgate you are correct. This behavior changed in 2.9 version. Do you like to submit PR?

**Comment by tcolgate** [comment] 2020-10-28 09:29
Sorry, I'm not going to have time, I'd need to understand things a bit better to be confident I'd not be breaking anything else.

**Comment by alexec** [comment] 2020-10-28 16:14
Can you try this image `argoproj/argocli:modes`. This now only uses an auth mode if the correct header is supplied AND the mode is enabled.

1. `Authorization: Bearer v2:.*` + `SSO` = `SSO`
2. `Authorization: Bearer .*` + `Client` = `Client`
3. `Authorization: Basic .*` + `Client` = `Client`
4. `Server` = `Server`

I'm not totally sure what you're set-up is, so this may fix you bug, or may not.

**Comment by dylanhellems** [comment] 2020-12-10 21:24
This fix appears to have been recently undone. Was that intentional? https://github.com/argoproj/argo/pull/4496/files

Works in v2.12.0-rc1 but seeing this issue again in later rcs.

**Comment by alexec** [comment] 2020-12-10 21:35
> This fix appears to have been recently undone.

Do you mean you can point to a specific change that undoes it? Or do you actually mean the problem has started to appear again?

**Comment by dylanhellems** [comment] 2020-12-10 21:44
Both. It looks like the additional checks for the current auth-mode were removed in the linked PR: https://github.com/argoproj/argo/pull/4496/files

**Comment by alexec** [comment] 2020-12-10 21:49
@simster7 -your PR?

**Comment by simster7** [comment] 2020-12-10 22:20
@dylanhellems I'm having a hard time seeing what the issue is just looking at the changes from the PR you linked. Can you elaborate a bit more on what the issue is, as well as what lines in particular you think affected it? Some steps to reproduce would also help.

**Comment by dylanhellems** [comment] 2020-12-10 22:36
The original fix for this issue added checks to the GetMode conditionals to ensure that it didn't try to use an inactive auth mode (see: the `&& m[Client]` in  https://github.com/argoproj/argo/pull/4412/files#diff-d26743300120981351842cdfdb25e21906ed62d3ca53c448ea6df863d7f1a90cR37).

The later PR removes those extra conditions (see: https://github.com/argoproj/argo/pull/4496/files#diff-d26743300120981351842cdfdb25e21906ed62d3ca53c448ea6df863d7f1a90cL37)

The problem is that if you send an Authorization header in a request to argo while using the "server" auth-mode, it will hit the client mode conditional and fail with a 401. This is a problem for our team since we are using istio as an authentication mechanism instead of argo's built-in auth, and istio is adding the header to requests.

**Comment by simster7** [comment] 2020-12-10 22:46
I see what you mean, I hadn't considered the validity of using Authorization headers while using server mode. I'll get a PR in soon and this will be fixed in the next release

**Closed** 2020-12-14 19:22 UTC
Labels: bug, more-information-needed

**Comment by simster7** [comment] 2020-12-15 19:01
@dylanhellems The fix for this was just released in RC6. Could I ask you to test?

**Comment by simster7** [comment] 2020-12-15 19:01
https://github.com/argoproj/argo/releases/tag/v2.12.0-rc6

**Comment by dylanhellems** [comment] 2020-12-17 16:21
@simster7 Working for me, thanks!
